name: Docker Image CI

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run curl command
      id: curl
      run: |
        OUTPUT=$(curl -s <URL>)
        echo "::set-output name=output::$OUTPUT"

    - name: Check if image with tag exists
      id: check
      run: |
        TAG_EXISTS=$(curl -s -f -u <DOCKER_USERNAME>:<DOCKER_PASSWORD> https://hub.docker.com/v2/repositories/<DOCKER_USERNAME>/<DOCKER_REPO>/tags/${{ steps.curl.outputs.output }} > /dev/null; echo $?)
        if [ "$TAG_EXISTS" -eq 0 ]; then
          echo "Image with tag '${{ steps.curl.outputs.output }}' already exists, exiting"
          exit 1
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        tags: <DOCKER_USERNAME>/<DOCKER_REPO>:${{ steps.curl.outputs.output }}
