name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
    - cron:  '34 17 * * 6'   # * is a special character in YAML so you have to quote this string
    # - cron:  '34 17 8-14,22-28 * 6'   # run every 2nd & 4th Saturday (by limiting Saturday to 2 date ranges)

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run curl command
      id: curl
      run: |
        verNum=$(curl -s https://nxfilter.org/curver.php)
        echo "NXFILTER_VER_NUM=$verNum" >> $GITHUB_OUTPUT
        # echo "::set-output name=output::$OUTPUT"

    - name: Login to DockerHub
      uses: docker/login-action@v3 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Check if image with tag exists
      id: check
      run: |
        TAG_EXISTS=$(curl -s -f -u ${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }} https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/nxfilter/tags/${{ steps.curl.outputs.NXFILTER_VER_NUM }} > /dev/null; echo $?)
        if [ "$TAG_EXISTS" -eq 0 ]; then
          echo "Image with tag '${{ steps.curl.outputs.NXFILTER_VER_NUM }}' already exists, exiting"
          exit 1
        fi

    - name: Run date command
      id: date
      run: |
        buildTime=$(date +%Y-%m-%d" "%X)
        echo "BUILD_TIME=$buildTime" >> $GITHUB_OUTPUT
        # echo "::set-output name=output::$DATE"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/nxfilter:${{ steps.curl.outputs.NXFILTER_VER_NUM }}
          ${{ secrets.DOCKERHUB_USERNAME }}/nxfilter:latest
        build-args: |
          VER_NUM=${{ steps.curl.outputs.NXFILTER_VER_NUM }}
          BUILD_TIME=${{ steps.date.outputs.BUILD_TIME }}
